### ISSUE TITLE
[BUG] AmberRst7.box_angles() objects have the wrong units

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#106]
Angles returned by the `box_angles()` method have length units:

```python
In [1]: import sire as sr

In [2]: s = sr.load_test_files("ala.crd", "ala.top")

In [3]: rst7 = sr.legacy.IO.AmberRst7(s._system)

In [4]: rst7.box_angles()
Out[4]: ( 90 Å, 90 Å, 90 Å )

In [5]: rst7.box_angles()[0].angle()
Out[5]: 0

In [6]: rst7.box_angles()[0].length()
Out[6]: 1
```

**Comment by chryswoods** [comment]
Good spot - this is in the python layer only, but is definitely annoying. The `Vector` class has some Python overrides that add length units to its components. I'll need to either remove these for this class or create a typed-vector interface for angles. For now, use `.value()` to get the raw doubles representing the angles in degrees.

**Comment by lohedges** [comment]
Great. I assumed it must be a Python layer thing since I've never had an issue with parsing anything, or creating spaces based on the box information. As suggested, I'm currently using `.value()`, then manually converting to degrees :+1:
