### ISSUE TITLE
Water models in prepareFEP.py

### ISSUE THREAD

**Issue by mark-cresset** [OpenBioSim/sire#112]
**Describe the bug**
When running prepareFEP.py, water models apart from TIP3P appear to be broken

**To Reproduce**

sire_python /path/to/share/Sire/scripts/prepareFEP.py --input1 Input1.parm7 Input1.dcd --input2 Input2.parm7 Input2.dcd --mapping mapping.txt --output Output --allow_ring_breaking True

**Expected behavior**
The prepareFEP call should run OK.

**Input files**
Input files attached as a zip file.

**(please complete the following information):**
 - OS: Linux (debian stable)
 - Version of sire:  2023.1.3_b3

**Additional context**
It looks like Sire tries to work out the water model based on the number of points, given the comments in _set_water_topology in _system.py. For 3-point models it seems to assume TIP3P. For 4-point models it assumes TIP4P, but the share/Sire/templates/water doesn't contain files for TIP4P, only for TIP4Pew. Renaming the "tip4pew.rst" and "tip4pew.prm7" to "tip4p.rst7" and "tip4p.prm7" seems to let things work OK. 

Questions: 

1) if the input parmtop was set up with e.g. SPC/E water, what (if anything) bad will happen here from Sire assuming that the water is in fact TIP3P?

2) Similarly, what (if anything) bad will happen from renaming the tip4pew files to tip4p?

[sire_bug.zip](https://github.com/OpenBioSim/sire/files/12894424/sire_bug.zip)

**Comment by lohedges** [comment]
Hi @mark-cresset. This should be fixed with the latest version of Sire. [Here](https://github.com/OpenBioSim/sire/tree/devel/corelib/templates/water) is the water template directory. I see:

```
ls -l corelib/templates/water/
total 72K
-rw-r--r-- 1 lester lester  187 Jan 26  2023 spce.gro87
-rw-r--r-- 1 lester lester  996 Jan 26  2023 spce.grotop
-rw-r--r-- 1 lester lester 2.6K Jan 26  2023 spce.prm7
-rw-r--r-- 1 lester lester  127 Jan 26  2023 spce.rst7
-rw-r--r-- 1 lester lester  186 Jan 26  2023 spc.gro87
-rw-r--r-- 1 lester lester 1.1K Jan 26  2023 spc.grotop
-rw-r--r-- 1 lester lester  188 Jan 26  2023 tip3p.gro87
-rw-r--r-- 1 lester lester 1.2K Jan 26  2023 tip3p.grotop
-rw-r--r-- 1 lester lester 2.6K Jan 26  2023 tip3p.prm7
-rw-r--r-- 1 lester lester  128 Jan 26  2023 tip3p.rst7
-rw-r--r-- 1 lester lester  233 Jan 26  2023 tip4p.gro87
-rw-r--r-- 1 lester lester 1.7K Jan 26  2023 tip4p.grotop
-rw-r--r-- 1 lester lester 2.8K May 23 14:09 tip4p.prm7
-rw-r--r-- 1 lester lester  166 May 23 14:09 tip4p.rst7
-rw-r--r-- 1 lester lester  278 Jan 26  2023 tip5p.gro87
-rw-r--r-- 1 lester lester 2.3K Jan 26  2023 tip5p.grotop
-rw-r--r-- 1 lester lester 3.0K Jan 26  2023 tip5p.prm7
-rw-r--r-- 1 lester lester  201 Jan 26  2023 tip5p.rst7
```

For your specific questions, I'm not sure. As you've found, the templating is currently just based on the number of atoms in the model, not the model itself. We can look at updating the logic to deal with this. Internally, if you solvate with BioSimSpace it will store the water model name as an attribute of the system and would pick the model based on that when swapping topology for another format. If you are loading things from outside of BioSimSpace, then we don't currently detect check anything other than the number of atoms.

**Comment by mark-cresset** [comment]
Hi Lester. Great - I'll look at pulling those in to our branch from the latest version. We're loading in pre-solvated systems from outside BSS.

**Comment by mark-cresset** [comment]
Ok, just checking the changelogs, it looks like the fix is just (as I had thought) renaming the tip4pew.* files to tip4p.*. That's easy enough to do.

**Comment by mark-cresset** [comment]
Hi Chris,

Yes, the fix that Lester mentioned fixes it completely.

Regards,
Mark

Mark Mackey
Chief Scientific Officer
Cresset
New Cambridge House, Bassingbourn Road, Litlington, Cambridgeshire, SG8 0SS, UK
Tel: +44 (0)1223 858890           Mobile: +44 (0)7595099165
Email: ***@***.******@***.***>     Web: www.cresset-group.com<http://www.cresset-group.com/>
