### ISSUE TITLE
Unable to Search for Atom Names Containing '

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/sire#115]
**Describe the bug**

I am trying to modify BioSimSpace so that specifying `restraint="backbone"` also works for nucleic acids. However, several nucleic acid backbone atoms contain ' in their names, which results in an error:

```
sys.search("atomname O5'")
```
Gives:
```
ValueError: 'Invalid search query: "atomname O5'" : SireMol::parse_error: Failed to parse any of the selection 'atomname 
O5''. (call sire.error.get_last_error_details() for more info)
```

I am doing this correctly? Apologies if I have missed this in the tutorials. Thanks very much.

**To Reproduce**

Here is my [RNA test system](https://github.com/OpenBioSim/sire/files/13039529/search_issue.tar.gz).

 - OS: Ubuntu 22.04
 - Version of Python: 3.11
 - Version of sire: 2023.4.0
 - I confirm that I have checked this bug still exists in the latest released version of sire: yes

**Comment by fjclark** [comment]
Thanks very much for the quick reply. Sorry I missed this in the docs.

**Comment by chryswoods** [comment]
No need to apologise - I didn't know the code could do that either ;-)

Initially I thought that I would have to write code to let us escape single quotes, e.g. `atomname O5\'`. Then, as I was writing a reply saying this wasn't supported, I thought maybe it would be ok in the regex code, so gave it a try. I was surprised and happy it worked.

I'm going to add some docs to the regex code and the tutorial to show how we can escape single quotes this way. I may also think about how to add proper escaping to the syntax, as it is surprising that it doesn't escape quotes.
