### ISSUE TITLE
[BUG] create_from_pertfile uses next instead of continue when skipping atoms that don't match the perturbation template

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#179]
When matching atoms to the perturbation template the current code incorrectly uses `next` to skip the atom in the case of a mismatch (see [here](https://github.com/OpenBioSim/sire/blob/d9d8f24c6187b53e0bd4eb78b05f00ba92c208d9/src/sire/morph/_pertfile.py#L90)). This will raise cause an `Exception` to be raised if the _first_ atom in the molecule isn't in the `atoms` section of the pert file, i.e. it is unperturbed. However, if there is a later mismatch, then the _wrong_ values of the end state `charge`,`LJ`, and `ambertype` will be applied to the atom. The solution is to replace `next` with `continue`.

**Comment by lohedges** [comment]
On a related not, I'm not sure if the error message that is printed when the atom is skipped is too useful. (Perhaps this is for debugging.) Since the `atom` records in the pert file only contains perturbing atoms, there will likely be many situations where atoms in the topology aren't matched. Perhaps there could be a verbose mode that prints what did and didn't match so that the user can cross-reference if they wish?

**Comment by chryswoods** [comment]
Thanks - good catch :-)

Yes, that error message was left over from debugging. I'll remove it and will then merge into devel.
