### ISSUE TITLE
[BUG] IFBOX pointer not set correctly for triclinic boxes

### ISSUE THREAD

**Issue by CHENFENG1020** [OpenBioSim/sire#215]
### Describe the bug:
When saving a solvated system to an Amber prm7 file, the IFBOX flag in the %FLAG POINTERS section is always set to 1, regardless of the box type used.
According to the Amber [Parameter-Topology file appendix](https://ambermd.org/prmtop.pdf) :

> IFBOX Flag indicating whether a periodic box is present. Values can be 0 (no box), 1 (orthorhombic box) or 2 (truncated octahedron)

### To Reproduce:
Build a truncated octahedron water box, save amber prm7 and rst7 file.
In prm7 file:

> Line 9:        0       0       0       0       0       0       0       1      X       0
1 is IFBOX value
X the number of atoms in the largest residue

At the end of the rst7 file:
>length length length 109.4711785  70.5287288  70.5287617

Run the simulation using the Amber engine. In the `mdout` file, a line in the RESOURCE USE section:

> BOX TYPE: RECTILINEAR

If check the wrapped trajectory, the box looks like this:
![image](https://github.com/user-attachments/assets/a631e61d-57d2-400f-8684-a382c8301105)

### Expected behavior:
1. prm7 file IFBOX flag set to 2
2. At the end of the rst7 file:
>length length length 109.4712190 109.4712190 109.4712190

*** The box angle must be set to 109.4712190 for Amber to recognize it correctly (Otherwise will have this in mdout file''Error: ifbox=2 in prmtop but angles are not correct''). Seems simply changing the angle in the rst7 file will cause the simulation to fail.

3. In mdout file:

> BOX TYPE: TRUNCATED OCTAHEDRON

4. If check the wrapped trajectory, the box should looks like truncated octahedron box:
![image](https://github.com/user-attachments/assets/96672224-f7ab-4110-8c21-a7e17508f3ad)

### Input files:
The zip contains three folders:
from_bss: This folder contains the system built by BSS. Also a short NPT eq results.
modified: In this folder, the prm7 file has been modified to change the IFBOX flag to 2, and the rst7 file has been modified to match amber required angles. Also failed simulation results.
from_amber: This folder contains a similar-sized system in truncated octahedron water box built by Amber TLEaP with short NPT eq results.
[test.zip](https://github.com/user-attachments/files/16363534/test.zip)

 - OS:Linux (unbuntu 24.4.0)
 - Version of Python: 3.12.3
 - Version of BioSimSpace: dev
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

### Additional context:
The IFBOX flag in the prm7 file is related to three other flags: SOLVENT POINTERS, ATOMS PER MOLECULE, and BOX DIMENSIONS.
However, it appears that as long as IFBOX is greater than 0, the data for the first two flags (SOLVENT POINTERS and ATOMS PER MOLECULE) will not be affected. The BOX DIMENSIONS flag will be affected, but it is deprecated as amber simulation now uses the box dimensions specified in the last line of the rst7 file.

**Comment by lohedges** [comment]
Ah yes, I see:

> *** The box angle must be set to 109.4712190 for Amber to recognize it correctly (Otherwise will have this in mdout file''Error: ifbox=2 in prmtop but angles are not correct''). Seems simply changing the angle in the rst7 file will cause the simulation to fail.

Well, that is certainly undesirable. Surely AMBER can support other triclinic boxes?

**Comment by lohedges** [comment]
Okay, we need to set it to 3 for a general triclinic box. See [here](https://github.com/ParmEd/ParmEd/issues/724) for details.

**Comment by lohedges** [comment]
Okay, this is only related to the legacy `corelib/src/libs/SireIO/amber.cpp` parser:

```
grep -r IFBOX corelib/src/libs/SireIO                                                       ✘ 2 fix_213_215 ✭ ✱ ◼
corelib/src/libs/SireIO/amber.cpp:    IFBOX = 27,  // set to 1 if standard periodic box, 2 when truncated octahedral
corelib/src/libs/SireIO/amber.cpp:                MBPER,  MGPER,  MDPER,  IFBOX,  NMXRS,  IFCAP
corelib/src/libs/SireIO/amber.cpp:    IFBOX  : set to 1 if standard periodic box, 2 when truncated octahedral
corelib/src/libs/SireIO/amber.cpp:    The following are only present if IFBOX .gt. 0
corelib/src/libs/SireIO/amber.cpp:    if (pointers[IFBOX] != 0)
corelib/src/libs/SireIO/amber.cpp:    if (pointers[IFBOX] != 0)
corelib/src/libs/SireIO/amber.cpp:    if (pointers[IFBOX] == 1)
corelib/src/libs/SireIO/amber.cpp:    else if (pointers[IFBOX] == 2)
```

I believe that this is only used by SOMD, so I'm confused how you get the wrong flag when writing to PRM7 with BioSimSpace, since that will use `Sire::IO::AmberPrm7`, which doesn't appear to use the pointer at all.

**Comment by lohedges** [comment]
Yes, there is nothing in the file. Could you explain how BioSimSpace is producing the files with the incorrect `IFBOX` flag?

```python
In [1]: import BioSimSpace as BSS

INFO:numexpr.utils:Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [2]: url = BSS.tutorialUrl()

In [3]: s = BSS.IO.readMolecules(BSS.IO.expand(url, ["ala.top", "ala.crd"]))
Downloading from 'https://biosimspace.openbiosim.org/m/ala.top'...
Unzipping '/tmp/tmpxbkn6qdx/ala.top.bz2'...
Downloading from 'https://biosimspace.openbiosim.org/m/ala.crd'...
Unzipping '/tmp/tmpxbkn6qdx/ala.crd.bz2'...

In [4]: box, angles = BSS.Box.truncatedOctahedron(3*BSS.Units.Length.nanometer)

In [5]: solvated = BSS.Solvent.tip3p(s[0], box=box, angles=angles)

In [6]: BSS.IO.saveMolecules("test", solvated, "prm7")
Out[6]: ['/home/lester/Code/openbiosim/biosimspace/test.prm7']
```

Then:

```
grep -ir IFBOX test.prm7 | wc -l
0
```

I assume that the AMBER process output is writing a default value of 1, so you are getting an incorrect visualisation.

**Comment by lohedges** [comment]
Ah, I see. Sorry for the confusion. Then yes, we need to write 3 in this section for a general triclinic space. Will see if I can fix now.

**Comment by lohedges** [comment]
Okay, this should now be fixed [here](https://github.com/OpenBioSim/sire/pull/216). I'll test with BioSimSpace and update the PR if there are any issues. I've just used a value of 3 for a general triclinic space, rather than detecting a truncated octahedraon and using 2 in that case. Hopefully this should work in general.
