### ISSUE TITLE
[BUG] Minimisation/Dynamics failing when using positional restraints

### ISSUE THREAD

**Issue by mb2055** [OpenBioSim/sire#232]
**Describe the bug**
Simulations fail when running  minimisation or dynamics on a perturbable system with positional restraints. 

**To Reproduce**
Run the following script:
```python
import sire as sr
system = sr.load(sr.expand(sr.tutorial_url, "merged_molecule.s3"))
system = sr.morph.link_to_reference(system)
restraints = sr.restraints.positional(system, atoms="element C")
system = system.minimisation(lambda_value=0.0, restraints=restraints).run().commit()
```
The error raised is: `ValueError: There was a problem creating the OpenMM context. Perhaps the platform was not supported for this system, options or on this computer? The error message is: CustomNonbondedForce: Wrong number of parameters 
for particle 12167`

**Expected behavior**
The script should minimise as expected, which it does if the `restraints` argument is removed.

**(please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - Version of Python: Python 3.12.4
 - Version of sire: 2024.3.0.dev
 - I confirm that I have checked this bug still exists in the latest released version of sire: yes

**Additional context**
The system in question contains exactly 12167 atoms. This implies that the issue here is in the additional ghost atoms added when using positional restraints.

**Comment by chabi-fin** [comment]
Hey, I see this is marked as complete, but I still get the same error. Do I need to use the dev branch? My sire version is '2024.2.0'.
