### ISSUE TITLE
Definition of Annihilation

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/sire#245]
This isn't a bug, but I wanted to ask about the definition of "annihilation" as implemented in [`sire.morph.annihilate()`](https://sire.openbiosim.org/api/morph.html#sire.morph.annihilate).

The documentation clearly says that "Annihilation is the process of turning off all interactions involving all of the atoms of the molecule being annihilated." ([here](https://sire.openbiosim.org/tutorial/part07/06_decouple.html#annihilation)), and corresponding the annihilated benzene in the example has intramolecular **bonded** interactions removed. 

However, I haven't seen this definition before for ABFE calculations. The two normal definitions (as far as I am aware) for ABFE are:

1. An ABFE calculation without restraints (as opposed to the "double decoupling" of [Gilson et al 1997](https://www.sciencedirect.com/science/article/pii/S0006349597787563?via%3Dihub)), which is now standard practice.
2. An ABFE calculation where intramolecular **non-bonded** interactions are removed (rather than only the intermolecular non-bonded components, as in the corresponding definition of "decoupling").

For a discussion of this, see the note given at ref 61 in [this paper](https://pubs.aip.org/aip/jcp/article/125/8/084902/916842). 

My questions are:

1. Why are bonded terms removed by `sire.morph.annihilate()`? Are there applications where it is useful? I see the tutorial mentions "The end state would represent non-interacting particles in harmonic wells, for which an analytical solution exists to calculate the free energy of annihilation.", requiring the user to set positional restraints for all atoms in the ligand.
2. Should we change this function to provide the likely expected behaviour, and rename the current function e.g. `annihilate_bonded`? I think users interested in ABFE will expect this function to remove some bonded terms, but not touch the bonded terms. It might make sense to have `decouple` and `annihilate` match the behaviour of `couple-intramol=no` and `yes` in GROMACS, respectively:
![image](https://github.com/user-attachments/assets/5ea018c9-4c25-4353-aa68-f0eaf0047217)

Thanks, and apologies if I'm misunderstanding!

**Comment by jmichel80** [comment]
tagging @chryswoods for his opinion

**Comment by chryswoods** [comment]
This comes from my very old definition of annihilation simulations. These do completely annihilate the molecule, and you do need to add harmonic restraints to each atom. They were used by Richard Sessions and Mike Tyka back in the day, and came from decouple meaning to detach (decouple) the molecule from the rest of the system, and annihilate meaning to completely destroy / remove the molecule. 

I am not wedded to the terms and am happy for the functions to be called whatever would now make sense and not confuse people.
