### ISSUE TITLE
[BUG] Sire-to-RDKit conversion issues

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#261]
I recently changed the logic for creating OpenFF molecules during the parameterisation pipeline in BioSImSpace to using the direct Sire-to-RDKit conversion functionality since this appeared to be more robust in certain cases. (It fixed several issues that were posted.) However, it appears that parameterisation is now failing for certain molecules that worked fine previously, i.e. when going via an intermediate SDF file. (These molecules are coming from SDF format initially.)

Having written a simple test script, it appears that it some cases the canonical SMILES representation of the molecule differs when creating an RDKit molecule via Sire-to-RDKit versus loading the molecule directly from SDF in RDKit. I've also tested the OpenFF RDKit molecule conversion, i.e. going from the RDKit molecule an OpenFF moleucle directly. In most cases where the SMILES differs this fails, but not always. When checking the OpenFF molecule in comparison to a molecule created loading the original SDF directly, the molecules are found to differ. This means that there is a pathway to create a parameterised molecule via OpenFF that (potentially) differs to what would obtained when going via SDF.

Here is the script:

```python
from glob import glob
from rdkit import Chem
from openff.toolkit import Molecule

import sire as sr

for sdf in sorted(glob("*.sdf")):
    fail = False

    # Read with Sire.
    mol = sr.load(sdf)

    # Convert to RDKit.
    rdmol = sr.convert.to_rdkit(mol)

    # Load the SDF with RDKit.
    rdmol_sdf = Chem.SDMolSupplier(sdf)[0]

    # Check the RDKit SMI and SDF are the same.
    if Chem.CanonSmiles(Chem.MolToSmiles(rdmol)) != Chem.CanonSmiles(
        Chem.MolToSmiles(rdmol_sdf)
    ):
        print(f"SMILES differ: {sdf}")
        fail = True

    # Read the SDF into OpenFF.
    off_mol_sdf = Molecule.from_file(sdf)

    # Convert from RDKit to OpenFF.
    try:
        off_mol_sire = Molecule.from_rdkit(rdmol)

        # Check if the OpenFF molecules are the same.
        if off_mol_sdf != off_mol_sire:
            print(f"Molecules differ: {sdf}")

    except Exception as e:
        print(f"Failed OpenFF conversion: {sdf}: {e}")
        fail = True
        continue

    if not fail:
        print(f"Success: {sdf}")

    print()
```

The inputs (and script) can be found [here](https://github.com/user-attachments/files/17917674/sire_rdkit_issue.tar.gz) should be:

```
Success: lig_23.sdf

SMILES differ: lig_2dd.sdf
Failed OpenFF conversion: lig_2dd.sdf: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: MOLUndefined chiral centers are:
 - Atom C (index 4)

SMILES differ: lig_2hh.sdf
Failed OpenFF conversion: lig_2hh.sdf: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: MOLUndefined chiral centers are:
 - Atom C (index 4)

SMILES differ: lig_2ii.sdf
Failed OpenFF conversion: lig_2ii.sdf: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: MOLUndefined chiral centers are:
 - Atom C (index 4)

SMILES differ: lig_2s.sdf
Failed OpenFF conversion: lig_2s.sdf: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: MOLBonds with undefined stereochemistry are:
 - Bond 31 (atoms 19-28 of element ({atom1.GetSymbol()}-{atom2.GetSymbol()})

SMILES differ: lig_2x.sdf
Molecules differ: lig_2x.sdf
```

So, `lig_23.sdf` converts correctly, i.e. both the SMILES and OpenFF molecules agree. Next, `lig_2x.sdf` has a mismatch with the SMILES, but OpenFF conversion works even though the resulting molecules differ. All other ligands have different SMILES _and_ cannot be converted to OpenFF format. (In all cases this is due to an "unspecified stereochemistry" error.)

It would be nice if the Sire-to-RDKit conversion functionality gave the same result as loading the SDF in RDKit directly (when the molecule is loaded from SDF into Sire). Clearly this _does_ work okay in many cases, so it would be good to work out what is going wrong in these instances. For now, I might revert the change in BioSimSpace. Ideally I could try both approaches, but the possibility of creating an invalid molecule in OpenFF is worrying.

**Comment by lohedges** [comment]
Just working my way through the atomic properties of the RDKit molecules to see where the differences are. Firstly, there is missing chirality info in the RDKit molecule created via Sire, so that probably explains why we fail to parameterise molecules with chiral centers, i.e.:

```python
import sire as sr
from rdkit import Chem

mol = sr.load("lig_2x.sdf")[0]
rdmol_sire = sr.convert.to_rdkit(mol)

rdmol_sdf = Chem.SDMolSupplier("lig_2x.sdf")[0]

for a0, a1 in zip(rdmol_sire.GetAtoms(), rdmol_sdf.GetAtoms()):
    print(a0.GetChiralTag(), a1.GetChiralTag()
```

Gives:

```
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_TETRAHEDRAL_CW
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
CHI_UNSPECIFIED CHI_UNSPECIFIED
```

So, sire is missing a `CHI_TETRAHEDRAL_CW` tag. I'll take a look at how they are set. Hopefully it's something simple, or a missing sanitization step.

**Comment by lohedges** [comment]
Also issues with the hybridization:

```
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP SP2
SP SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP3
SP3 SP3
SP3 SP3
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP2
SP2 SP3
SP SP3
SP SP3
SP2 SP3
SP2 SP3
```

**Comment by lohedges** [comment]
Okay, it looks like this is because the `chirality` and `hybridization` atomic properties aren't set when reading a molecule from SDF file. These are recovered when converting from the correct RDKit molecule to Sire. So, I'll need to work out how these are inferred/set in RDKit, then do the same when creating the molecule with Sire. Presumably the info exists in the SDF, or is inferable, so I'll look into how to do this, i.e. not just setting them to null values when the atomic properties are missing.

**Comment by lohedges** [comment]
It's even worse, there is no round-trip self-consistency in the RDKit conversion at all. For example, if you take the _correct_ RDKit molecule and convert it to Sire then the Sire molecule _does_ have the correct `chirality` and `hybridization` properties afterwards, but these are lost (or set incorrectly) when converting back to RDKit, ie..:

```python
import sire as sr
from rdkit import Chem

mol = sr.load("lig_2x.sdf")[0]
rdmol_sire = sr.convert.to_rdkit(mol)

rdmol_sdf = Chem.SDMolSupplier("lig_2x.sdf")[0]

for a0, a1 in zip(rdmol_sire.GetAtoms(), rdmol_sdf.GetAtoms()):
    if a0.GetChiralTag() != a1.GetChiralTag():
        print(a0.GetChiralTag(), a1.GetChiralTag())
    if a0.GetHybridization() != a1.GetHybridization():
        print(a0.GetHybridization(), a1.GetHybridization())

# Convert back from RDKit to Sire
mol2 = sr.convert.to_sire(rdmol_sdf)

# Check that the chirality and hybridization properties are set.
assert mol2.has_property("chirality")
assert mol2.has_property("hybridization")

# Convert back to RDKit again.
rdmol_sire2 = sr.convert.to_rdkit(mol2)

# Now compare the chirality and hybridization properties again.
print()
for a0, a1 in zip(rdmol_sire2.GetAtoms(), rdmol_sdf.GetAtoms()):
    if a0.GetChiralTag() != a1.GetChiralTag():
        print(a0.GetChiralTag(), a1.GetChiralTag())
    if a0.GetHybridization() != a1.GetHybridization():
        print(a0.GetHybridization(), a1.GetHybridization())
```

Gives:

```
SP SP2
SP SP2
SP2 SP3
CHI_UNSPECIFIED CHI_TETRAHEDRAL_CW
SP2 SP3
SP SP3
SP SP3
SP2 SP3
SP2 SP3

SP SP2
SP SP2
SP2 SP3
CHI_UNSPECIFIED CHI_TETRAHEDRAL_CW
SP2 SP3
SP SP3
SP SP3
SP2 SP3
SP2 SP3
```

So, we end up with the exact same invalid RDKit molecule. I've added debugging statements to the Sire-to-RDKit converter and see that the propeties are being set in RDKit via `setChiralTag` and `setHybridization` for the second pass, i.e. when the atomic properties _are_ present in Sire, so I'm not sure why they end up being wrong in the molecule that is generated.

**Comment by lohedges** [comment]
With this diff, the second bit works, i.e. the correct resulting RDKit molecule has the correct chirality and hybridisation:

```
diff --git a/wrapper/Convert/SireRDKit/sire_rdkit.cpp b/wrapper/Convert/SireRDKit/sire_rdkit.cpp
index f5574cdc..a5ddbfe5 100644
--- a/wrapper/Convert/SireRDKit/sire_rdkit.cpp
+++ b/wrapper/Convert/SireRDKit/sire_rdkit.cpp
@@ -841,7 +841,7 @@ namespace SireRDKit

         try
         {
-            RDKit::MolOps::setHybridization(molecule);
+            //RDKit::MolOps::setHybridization(molecule);
         }
         catch (...)
         {
@@ -849,7 +849,7 @@ namespace SireRDKit

         try
         {
-            RDKit::MolOps::cleanupChirality(molecule);
+            //RDKit::MolOps::cleanupChirality(molecule);
         }
         catch (...)
         {
```

I'm not sure why calling these functions ends up changing the values when they have been set correctly in the first place. Maybe they should only be called if the atomic properties are unset in the first place?

**Comment by lohedges** [comment]
Yes, the invalid values are just what is set by calling `Chem.SetHybridization` and `Chem.CleanupChirality`. I've confirmed this using the RDKit Python API. The same thing happens when just sanitizing the molecule with `Chem.SanitizeMol`. Clearly this is the problem, since we are always sanitizing things _regardless_ of whether the properties have been set. Perhaps we need to keep track of whether we've set the chirality and hybridisation, etc., then only call the relevant functions if not. This should fix the round-trip self-consistency issue. (Assuming the properties are correct.) The other issue is how to set these in the first place, i.e. using the info from the SDF alone. I've not yet found how RDKit is doing this, but could follow the same logic if it's easy (or directly call the relevant RDKit functions).

**Comment by lohedges** [comment]
Not sure if the atom ordering is different here, but it seems that the bonding set by Sire disagrees with what RDKit sets:

```pythoun
import sire as sr
from rdkit import Chem

mol = sr.load("lig_2x.sdf")[0]
rdmol_sire = sr.convert.to_rdkit(mol)

rdmol_sdf = Chem.SDMolSupplier("lig_2x.sdf")[0]

print("Sire")
for bond in rdmol_sire.GetBonds():
    print(
        bond.GetBeginAtomIdx(),
        bond.GetEndAtomIdx(),
        bond.GetBondType(),
        bond.GetStereo(),
    )

print("\nRDKit")
for bond in rdmol_sdf.GetBonds():
    print(
        bond.GetBeginAtomIdx(),
        bond.GetEndAtomIdx(),
        bond.GetBondType(),
        bond.GetStereo(),
    )
```

Gives:

```
Sire
0 2 DOUBLE STEREONONE
0 6 SINGLE STEREONONE
1 11 AROMATIC STEREONONE
1 18 DOUBLE STEREONONE
1 19 AROMATIC STEREONONE
2 12 SINGLE STEREONONE
2 14 SINGLE STEREONONE
3 17 AROMATIC STEREONONE
3 20 AROMATIC STEREONONE
3 21 SINGLE STEREONONE
4 5 AROMATIC STEREONONE
4 9 AROMATIC STEREONONE
4 10 AROMATIC STEREONONE
5 11 AROMATIC STEREONONE
6 7 DOUBLE STEREONONE
6 15 SINGLE STEREONONE
7 8 DOUBLE STEREONONE
8 12 DOUBLE STEREONONE
9 19 AROMATIC STEREONONE
9 20 AROMATIC STEREONONE
10 17 AROMATIC STEREONONE
11 16 SINGLE STEREONONE
12 16 SINGLE STEREONONE
13 19 SINGLE STEREONONE
21 22 SINGLE STEREONONE
22 23 AROMATIC STEREONONE
22 26 AROMATIC STEREONONE
23 24 TRIPLE STEREONONE
24 25 AROMATIC STEREONONE
25 26 AROMATIC STEREONONE

RDKit
0 2 AROMATIC STEREONONE
0 6 AROMATIC STEREONONE
1 11 AROMATIC STEREONONE
1 18 DOUBLE STEREONONE
1 19 AROMATIC STEREONONE
2 12 AROMATIC STEREONONE
2 14 SINGLE STEREONONE
3 17 AROMATIC STEREONONE
3 20 AROMATIC STEREONONE
3 21 SINGLE STEREONONE
4 5 AROMATIC STEREONONE
4 9 AROMATIC STEREONONE
4 10 AROMATIC STEREONONE
5 11 AROMATIC STEREONONE
6 7 AROMATIC STEREONONE
6 15 SINGLE STEREONONE
7 8 AROMATIC STEREONONE
8 12 AROMATIC STEREONONE
9 19 AROMATIC STEREONONE
9 20 AROMATIC STEREONONE
10 17 AROMATIC STEREONONE
11 16 SINGLE STEREONONE
12 16 SINGLE STEREONONE
13 19 SINGLE STEREONONE
22 21 SINGLE STEREONONE
22 23 SINGLE STEREONONE
22 26 SINGLE STEREONONE
23 24 SINGLE STEREONONE
24 25 SINGLE STEREONONE
25 26 SINGLE STEREONONE
```

As far as I can tell, this info _is_ set from fields in the SDF file, so might well be used to infer missing hybridisation and chirality tags. If the bonding is wrong, then presumably everything that follows will also be wrong.

**Comment by lohedges** [comment]
The issue is that it appears to be reading the bond order from the SDF file, but isn't using it when creating the RDKit molecule.There is a `has_bond_info` flag that should be `true` when this information is present, but it is `false` in this case. When `false` it falls back on the algorithm from MDAnalysis to infer the missing bond info, which clearly isn't 100% reliable.

I'll try to work out why it's failing to use the existing property.

**Comment by lohedges** [comment]
Aha, the flag was never being set to `true`, so that's why it never used the existing bond order info, i.e. it was incorrectly being set to `false` when the property was found. Now almost everything is working. It is still giving invalid chiral tags though, so I'm not sure what else RDKit uses to assign those. (Other than the `Chem.CleanupChirality` function.)

**Comment by lohedges** [comment]
I've managed to fix it for _every_ problem input that has been provided. To do so, I needed to change the code so that implicit hydrogens were allowed and, when coordinates were present, assigned the stereochemistry using the coordinates via `RDKit::MolOps::assignStereochemistryFrom3D(molecule)`. In all cases, this gives the _exact_ same canonical SMILES as is obtained when loading the SDF with RDKit directly and all molecules can be converted to OpenFF and parameterised as required.

However, this change now breaks the existing RDKit tests. These are due to mismatches in SMILES strings between the new and old molecules from `sr.smiles`, the other is a SMILES mismatch in the `infer_bonds` function. I'll try to figure out why these are different, and whether the issue can be resolved by canonicalising.

**Comment by lohedges** [comment]
Ah, I see. By default, RDKit retains some hydrogens in the SMILES that are important for defining stereochemistry. These can be removed by an additional kwarg. I can either add this to the `.smiles()` method, or just update the tests with the new SMILES strings. Will have a think.

**Comment by lohedges** [comment]
I think we'll need another option for the `infer_bonds` test. It's failing because the SDF conversion now has the correct stereochemistry, so the SMILES string is different to the one obtained when going via a GROMACS format, which doesn't have the stereo information.

I'll add some tests to the BioSImSpace suite based on the changes. (Will PR when done.) This should show that the conversion is robust.

**Comment by lohedges** [comment]
I've now added a test to check that SDF stereochemistry is preserved on conversion to RDKit with Sire [here](https://github.com/OpenBioSim/biosimspace/commit/62e53338c1b0c8bf02d07746539374b888015cbe). These molecules now parameterise, although it is too slow to add this to the tests.

For now I've XFailed the `test_rdkit_infer_bonds` test since the new SMILES string generated from the SDF molecule contains stereo information that isn't present in the GROMACS one, hence the mismatch. We could probably generate other input, or use a regex to strip the extra characters from the string.

@chryswoods: Let me know if you have any issues with any of the changes required for this fix, or if there are any things that I've not thought about. As noted above, 2D SMILES (and hence 2D depictions) from molecules will now have stereo bonds. I think this will actually fix some issues that were raised (privately) by Exs members, where the visualisation didn't agree with what they were getting from elsewhere. (I think you do have `AssignStereochemistryFrom3D` in the 2D view Python layer, though.)

**Comment by chryswoods** [comment]
Thanks Lester - this all looks great. Thanks for going down the rabbit hole to make everything consistent. I think the approach you took is the right one, and there isn't much that can be done about the gromacs test. I agree it is better to  xfail it for now and we can think about it later. It's nice that the 2D views have better stereochemistry and better match what Exs would expect.
