### ISSUE TITLE
[BUG] AmberPrm parser segfaults if RESIDUE_LABEL flag is empty

### ISSUE THREAD

**Issue by xiki-tempula** [OpenBioSim/sire#42]
**Describe the bug**
Sorry for pushing this bug to you. It is a interchange 0.3 issue. Do you mind chat with the interchange people to fix this issue? Thanks.

**To Reproduce**
Create a new environment `mamba create -n test -c conda-forge -c OpenBioSim/label/dev biosimspace=2023.2 AmberTools`
```
import BioSimSpace as BSS
BSS.Parameters.parameterise("c1ccccc1C(=O)[O-]", "openff_unconstrained-2.0.0").getMolecule()
```
Gives
Segmentation fault (core dumped)

**Expected behavior**
Runs

**(please complete the following information):**
 - OS: Linux (distribution)
 - Version of Python: 3.8
 - Version of BioSimSpace: 2023.2
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: [yes/no]

**Additional context**

**Comment by lohedges** [comment]
For reference, it looks like they have recently made some changes to the logic to generated residue labels [here](https://github.com/openforcefield/openff-interchange/commit/6025b546c9fa96ae0d1dd763fcf31be56f559b46). I assume that this isn't working correctly. I'll create a minimal example and raise an issue there.

**Comment by lohedges** [comment]
I've now reported the issue at the link above.

**Comment by chryswoods** [comment]
It was an easy fix - test added, pull request submitted and we'll wait to see if it all works before accepting into `devel` / `main` :-)

**Comment by lohedges** [comment]
This has now been fixed in OpenFF and will appear in version `0.3.1` within the next few weeks. This should mean that older builds of Sire should work again.

**Comment by xiki-tempula** [comment]
Great. Thanks. So Sire 2023.2.2 would work with openff-interchange 0.3?

**Comment by xiki-tempula** [comment]
Great thanks
