### ISSUE TITLE
[BUG] sire_bigtests/SireQt/test_timer.py failing on Windows

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#54]
In the process of creating the `2023.2.3` release I ran [sire_bigtests](https://github.com/OpenBioSim/sire_bigtests) against the release builds on all platforms. All passed, except for Windows where I see the following failure for all Python variants:

```
test_timer.test_timer ... FAIL

======================================================================
FAIL: test_timer.test_timer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda3\envs\sire_build\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "D:\a\sire_bigtests\sire_bigtests\tests\SireQt\test_timer.py", line 33, in test_timer
    assert ns >= 990000000
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Minimum time is 0.0010999999999999998 ms
Slept for 1 s == 989.5609999999999 ms
```

(See [here](https://github.com/OpenBioSim/sire_bigtests/actions/runs/4981860818/jobs/8916705596) for the full log.)

This is a legacy test, i.e. it doesn't test new functionality, or anything that was updated for this patch release. The run used the exact same version of `qt-main` as the last successful build, i.e. `5.15.8`.

(The `2023.2.3` packages are now labelled with `main` and `test` since I wanted to get out working BioSimSpace builds for the platforms that do work.)

**Comment by lohedges** [comment]
I've checked the CI runner info and the same OS and build was used for both too, i.e.:

```
Microsoft Windows Server 2022
  10.0.20348
```

This is the case for the `sire_bigtests` run, and for the Sire release build (both for versions `2023.2.2` and `2023.2.3`). The same version of Visual Studio code and `choclatey` were used too.

**Comment by chryswoods** [comment]
Yes - I think I should remove this test. All it has done is show that sleep timers are not as precise as we would hope. This was important way back in sire's past, but I don't think anything relies on sleeping any more.

**Comment by chryswoods** [comment]
Yes - I think I should remove this test. All it has done is show that sleep timers are not as precise as we would hope. This was important way back in sire's past, but I don't think anything relies on sleeping any more.

**Comment by lohedges** [comment]
At some point, would you be able to debug the BioSimSpace `setup.py` issue on your Windows VM? The logic to install missing dependencies via the `setup.py` seems to work on Linux and macOS, but not Windows. This isn't an issue for the BioSimSpace CI, since the dependencies are always installed via the `conda` recipe.

**Comment by chryswoods** [comment]
Yes - I'll take a look

**Comment by chryswoods** [comment]
Closing as I have removed the test, and have raised a PR in BioSimSpace that fixes the setup.py issues :-)
