### ISSUE TITLE
[BUG] SMILES conversion can return an empty molecule

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#58]
I assume this is because the SMILES conversion is failing, but it's possible to get back an empty molecule, e.g:

```python
In [1]: import sire as sr

In [2]: sr.smiles("c3cc[c+]2cc(C1CCCC1)[nH]c2c3")

[13:03:23] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 12 13
Out[2]: Molecule( :0      num_atoms=0 num_residues=0 )
```

If an exception was raised by `rdkit` then it would be good if this was caught. From working with BioSimSpace, I know that `rdkit` often doesn't raise an exception and just returns nothing, so it might be necessary to check for this too.

If I go via `rdkit` directly, then I see the following:

```python
In [1]: from rdkit import Chem

In [2]: rdmol = Chem.MolFromSmiles("c3cc[c+]2cc(C1CCCC1)[nH]c2c3")
[13:05:40] Can't kekulize mol.  Unkekulized atoms: 0 1 2 4 5 12 13

In [3]: type(rdmol)
Out[3]: NoneType
```

**Comment by chryswoods** [comment]
I'll take a look at this in the `fix_58` branch.

**Comment by chryswoods** [comment]
I've raised a pull request with the fix. This adds a `must_sanitize` flag (default True) to `sr.smiles()`. We now get an exception if the molecule doesn't sanitize. It is currently a `ValueError`, but I am open to changing this (I struggle choosing Python exceptions as I don't want to create new ones that are specific to sire, but many of the default exceptions also feel wrong).

If `must_sanitize` is False, then we now run sanitization manually, skipping steps that individually fail. This results in a molecule, but the coordinates and 2D structure are pretty poor...
