### ISSUE TITLE
Add read/write support for Schrödinger MAE format files

### ISSUE THREAD

**Issue by chryswoods** [OpenBioSim/sire#64]
We'd like to support reading and writing for Schrödinger MAE (and MAEGZ) files. There is an [open source reader](https://github.com/schrodinger/maeparser) for the underlying data structure, and an [openbabel implementation](https://github.com/openbabel/openbabel/pull/1993/files#diff-1f179e7f22017dbdcbafd7bf17603866d526319946030270708fe8d5acefb88d) that includes test files and shows how the keys relate to the molecular data.

**Describe the solution you'd like**
A working parser so that we can use `sire.load()` and `sire.save()` for MAE and MAEGZ type files.

**Describe alternatives you've considered**
We could look at wrapping OpenBabel and use that to convert file formats that we don't natively support. The file format is relatively simple, so a native solution shouldn't be too difficult.

**Comment by chryswoods** [comment]
I'm archiving this as I haven't had a chance to look at it. It can be revived later if there is interest.

**Comment by lohedges** [comment]
If we ever want to revisit this, there is now [this](https://github.com/SimonBoothroyd/pymaeparser) package that could be useful.
