### ISSUE TITLE
[BUG] Incorrect unit conversion for temperatures

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#73]
This works using the legacy API, but not with the new string grammar.

New units grammar:
```python
In [1]: from sire import u as unit

In [2]: temp = unit("kelvin")

In [3]: print(temp)
1 K

In [4]: temp.to("celsius")
Out[4]: 1.0
```

Direct conversion using legacy units:

```python
In [1]: import sire.units as units

In [2]: temp = units.kelvin

In [3]: print(temp)
1 K

In [4]: temp.to(units.celsius)
Out[4]: -272.15
```

**Comment by lohedges** [comment]
I guess this is probably due to a different handling of _offset_ units. However, I would expect both approaches to give the same result. In BioSimSpace I default to allowing operations between offset units, i.e. I convert to kelvin before doing an operation then convert back.

**Comment by chryswoods** [comment]
I've fixed this in the commit to `devel` (I accidentally pushed there rather than the `fix_73` branch I'd created because I was in the wrong directory...)

It was just because I had not initialised the temperatures to `1.0` when doing the temperature conversion from a string.

**Comment by lohedges** [comment]
Ah great, glad it was nice and easy. Thanks!

**Comment by chryswoods** [comment]
Sorry for not going through the PR route - I rushed it before the end of my lunch break and realised I had pushed to the wrong branch when I got the branch protections warning message.

Fortunately it was a tiny fix ;-)
