### ISSUE TITLE
Frame number in NGLView?

### ISSUE THREAD

**Issue by chryswoods** [OpenBioSim/sire#83]
New feature request - adding the frame number of a trajectory (and possibly the time data?) to the NGLView widget, so it is easier to find a particular frame, and then extract it in the next cell.

**Describe the solution you'd like**
The trajectory frame number should just appear in one corner of the NGLView widget, and should change as the trajectory is played.

**Comment by lohedges** [comment]
Nice, I think this would be really helpful.

**Comment by chryswoods** [comment]
I've just noticed that NGLView already shows a frame number! It is in a black font, which is why I didn't see it (as we use a black background).

I'm looking into the docs to see how to change the font colour. Interestingly, I've found on [this tutorial](https://projects.volkamerlab.org/teachopencadd/talktorials/T017_advanced_nglview_usage.html) that you can execute JS code from Python using a convenient interface in NGLView.

**Comment by chryswoods** [comment]
I'm archiving this as I haven't had a chance to look at it. It can be revived later if there is interest.
