### ISSUE TITLE
[BUG] Sire.IO.PDB2 not handling systems with more than 100000 atoms

### ISSUE THREAD

**Issue by cespos** [OpenBioSim/sire#84]
**Describe the bug**
If a system has more than 100'000 atoms, BioSimSpace.IO.saveMolecules() messes up the PDB format

**To Reproduce**
```
import BioSimSpace as BSS

ligand_coord = BSS.IO.readMolecules('aspirine.sdf')[0]
ligand = BSS.Parameters.parameterise(ligand_coord, 'gaff2').getMolecule()
box = [110 * BSS.Units.Length.angstrom] * 3
angles = [90 * BSS.Units.Angle.degree] * 3
solvated = BSS.Solvent.solvate('tip3p', ligand, box=box, angles=angles)
BSS.IO.saveMolecules("test.pdb", solvated , 'pdb')
```

**Expected behavior**
Correct PDB formatting

**Input files**
aspirine.sdf (Can be downloaded from [Pubchem](https://pubchem.ncbi.nlm.nih.gov/compound/Aspirin#section=3D-Conformer))

**(please complete the following information):**
 - Ubuntu
 - Version of Python: 3.10.12
 - Version of BioSimSpace: 2023.3.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: [yes/no] yes

**Additional context**
![image](https://github.com/OpenBioSim/biosimspace/assets/31316943/a8cbc8e0-2875-466f-ab35-bbc3b43cfd12)

**Comment by lohedges** [comment]
This is caused by the renumbering of atoms when TER records are detected. The original serial is set correctly, but then the same capping isn't applied when renumbering.

**Comment by lohedges** [comment]
I've fixed this on the [fix_84](https://github.com/OpenBioSim/sire/tree/fix_84) branch. I'm just checking that there aren't any unexpected side effects.

**Comment by chryswoods** [comment]
Ok - I will wait for this for `2023.3.1`
