### ISSUE TITLE
analyse_freenrg with TI is incorrect when simulation times are unequal

### ISSUE THREAD

**Issue by fjclark** [OpenBioSim/sire#85]
**Describe the bug**

When simulations at different lambda windows are not all run for an equal amount of time, the TI result from `analyse_freenrg` is incorrect by up to several kcal / mol. This is because the arrays used to hold the gradients [are initialised with zeros](https://github.com/OpenBioSim/sire/blob/19ba5a1d25aa638f02019b530b79bc064cecdbd4/wrapper/python/scripts/analyse_freenrg.py#L759) according to the length of the longest simulation. For all simulations other than the longest, the last values will remain 0. This means that [when finding the mean](https://github.com/OpenBioSim/sire/blob/19ba5a1d25aa638f02019b530b79bc064cecdbd4/wrapper/Tools/FreeEnergyAnalysis.py#L91), the result is much closer to 0 than it should be.

I will submit a PR to fix this shortly.

**(please complete the following information):**
 - Version of sire: latest `dev` release
 - I confirm that I have checked this bug still exists in the latest released version of sire: yes

**Comment by chryswoods** [comment]
I'll close this issue as the fix is now merged into `devel` and `main` (and released in 2023.3.1)
